### ISSUE TITLE
use forester config to generate new `*.lagda.tree`

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/agda-tree#8]
This can help us avoid name conflict, maybe need to use `forester query`, maybe @kentookura know more about this.

**Comment by dannypsnl** [comment]
Roughly I believe `query` will work badly, since it can only provides a JSON, I have to parse *again*. I probably need a `forester query prefix=tt`.

**Comment by kentookura** [comment]
Can you clarify what you want to happen? Do you want forester or your agda-tree tool to generate a `*.lagda.tree` file? Forester does not care if there are extra fields in the config file, so you can use it to configure agda-tree with additional info.

In any case, `forester query` is likely to change in the future to be a cli for the new query language.

**Comment by dannypsnl** [comment]
The issue is trying to use `agda-tree` to generate new file, that sounds like a bad idea right now to me, creates a tree via forester than move it already good enough.
